import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, MessageCircleMore } from "lucide-react";
import { toast } from "sonner";

const modes = [{ key: "objective", label: "Objetivo", description: "Vai direto ao ponto, sem perder a educação." }, { key: "balanced", label: "Equilibrado", description: "Explica o necessário e conduz com clareza." }, { key: "consultative", label: "Consultivo", description: "Mais acolhedor, detalhado e orientador." }] as const;

export function BehaviorModePanel({ config, onSaved }: { config: any; onSaved: () => void }) {
  const update = trpc.agent.updateConfig.useMutation({ onSuccess: () => { toast.success("Modo de comportamento atualizado."); onSaved(); } });
  const saveMode = (behaviorMode: "objective" | "balanced" | "consultative") => update.mutate({ agentId: config.agent.id, name: config.agent.name, persona: config.agent.persona, companyInfo: config.agent.companyInfo, services: config.agent.services, pricing: config.agent.pricing, businessHours: config.agent.businessHours, transferKeyword: config.agent.transferKeyword, ownerTakeoverCommand: config.agent.ownerTakeoverCommand, websiteUrl: config.agent.websiteUrl || undefined, instagramHandle: config.agent.instagramHandle || undefined, templateKey: config.agent.templateKey, behaviorMode, provider: config.agent.provider, modelPreference: config.agent.modelPreference });
  return <section className="mt-6 rounded-2xl border border-[#e3ece6] bg-white p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold">Modo de comportamento</p><p className="mt-1 text-sm text-muted-foreground">Todos os modos preservam respeito, gentileza e o direito do interlocutor de pedir uma pessoa.</p></div><MessageCircleMore className="size-5 text-primary" /></div><div className="mt-5 grid gap-3 md:grid-cols-3">{modes.map(mode => { const active = config.agent.behaviorMode === mode.key; return <button key={mode.key} onClick={() => saveMode(mode.key)} disabled={update.isPending} className={`rounded-xl border p-4 text-left transition ${active ? "border-primary bg-emerald-50" : "border-[#e5ece7] hover:border-emerald-200"}`}><div className="flex items-center justify-between"><p className="text-sm font-bold">{mode.label}</p>{active ? <Badge className="bg-primary">Ativo</Badge> : <CheckCircle2 className="size-4 text-slate-300" />}</div><p className="mt-2 text-xs leading-5 text-muted-foreground">{mode.description}</p>{active && <span className="mt-3 block text-xs font-semibold text-primary">Selecionado</span>}</button>; })}</div></section>;
}
